#!/usr/bin/env bash
# rebuild-state.sh — Regenerate tasks/_state.yaml from frontmatter scan.
#
# This is the recovery script. If _state.yaml is corrupt or out-of-sync,
# run this to rebuild it from the authoritative source (frontmatter).
#
# Safe to run anytime. Non-destructive. Always converges.

set -euo pipefail

# shellcheck source=./_lib.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_lib.sh"
ts_version_flag "$@"

TASKS_DIR="$TASKSPEC_BACKLOG_DIR"
STATE_FILE="${TASKS_DIR}/_state.yaml"

if [[ ! -d "$TASKS_DIR" ]]; then
  echo "ERROR: no $TASKS_DIR/ directory found in $(pwd)" >&2
  exit 1
fi

TS="$(date -u +%FT%TZ)"

TMP="${STATE_FILE}.tmp.$$"
ts_prepare_tmp "$TMP"

{
  echo "# Auto-generated by rebuild-state.sh — DO NOT EDIT DIRECTLY"
  echo "# Source of truth: frontmatter in each tasks/T-*.md"
  echo "schema_version: 1"
  echo "last_rebuilt: $TS"
  echo ""
  echo "tasks:"
} > "$TMP"

READY=()
IN_PROGRESS=()
BLOCKED=()
DONE=()
PARKED=()

TOTAL=0

# Scan every T-*.md anywhere under tasks/ (root + queue/ + done/ + parked/ +
# skill/ + kimi/ + feature/ + archive/ + any future subdir). Recursive find so
# new task folders are indexed automatically without editing this script.
while IFS= read -r FILE; do
  [[ -f "$FILE" ]] || continue

  ID=$(grep '^id:' "$FILE" | head -1 | awk '{print $2}' || echo "")
  STATUS=$(grep '^status:' "$FILE" | head -1 | awk '{print $2}' || echo "unknown")
  EFFORT=$(grep '^effort:' "$FILE" | head -1 | awk '{print $2}' || echo "?")
  AGENT=$(grep '^agent:' "$FILE" | head -1 | awk '{print $2}' || echo "any")

  [[ -z "$ID" ]] && continue

  TOTAL=$((TOTAL + 1))

  {
    echo "- id: ${ID}"
    echo "  path: ${FILE}"
    echo "  status: ${STATUS}"
    echo "  effort: ${EFFORT}"
    echo "  last_validated: ${TS}"
    echo "  validator_version: rebuild"
  } >> "$TMP"

  case "$STATUS" in
    ready) READY+=("$ID") ;;
    in-progress) IN_PROGRESS+=("$ID") ;;
    blocked) BLOCKED+=("$ID") ;;
    done) DONE+=("$ID") ;;
    parked) PARKED+=("$ID") ;;
  esac
done < <(find "$TASKS_DIR" -type f -name 'T-*.md' | sort)

{
  echo ""
  echo "ready_queue:"
  for id in "${READY[@]:-}"; do [[ -n "$id" ]] && echo "  - $id"; done

  echo ""
  echo "in_progress:"
  for id in "${IN_PROGRESS[@]:-}"; do [[ -n "$id" ]] && echo "  - $id"; done

  echo ""
  echo "blocked:"
  for id in "${BLOCKED[@]:-}"; do [[ -n "$id" ]] && echo "  - $id"; done

  echo ""
  echo "stats:"
  echo "  total: $TOTAL"
  echo "  ready: ${#READY[@]}"
  echo "  in_progress: ${#IN_PROGRESS[@]}"
  echo "  blocked: ${#BLOCKED[@]}"
  echo "  done: ${#DONE[@]}"
  echo "  parked: ${#PARKED[@]}"
} >> "$TMP"

mv "$TMP" "$STATE_FILE"

echo ">>> Rebuilt $STATE_FILE"
echo "    total: $TOTAL | ready: ${#READY[@]} | in_progress: ${#IN_PROGRESS[@]} | blocked: ${#BLOCKED[@]} | done: ${#DONE[@]} | parked: ${#PARKED[@]}"
