# {PROJECT_NAME} — AGENTS.md

> Cross-tool agent index for this repository.
> Generated by [agents-kbs-tech-stack](https://github.com/) — do not hand-edit.

## Scope

This repository ships a multi-tool-portable agent layer:

- **Architect agents** — planning, trade-off analysis, ADRs. No Bash. One per tech.
- **Developer agents** — implementation, tests, fixes. Has Bash. One per tech.
- **Troubleshooter agents** *(optional, per-tech)* — incident response, root-cause analysis. Tech-specific.
- **Closer agents** — universal pre-merge polish (code review, simplification, documentation). Ground in every tech KB at runtime via the closer-hook protocol.

The agents live under `.claude/agents/` and ground in knowledge bases under `.claude/kb/`. This file is the index every cooperating tool reads first (Claude Code, Cursor, GitHub Copilot, Codex, etc. — see the [AGENTS.md convention](https://agents.md/)).

## Agents

{AGENTS_TABLE}

## Knowledge Base

{KB_TABLE}

## Conventions

- **Doctrine:** see [`.claude/doctrine.yaml`](.claude/doctrine.yaml) for the portable agent contract (Bash boundary, threshold floors, closer-hook protocol). Tools that honor AGENTS.md should also honor doctrine.yaml.
- **Source of truth:** `.claude/agents/` (agents) and `.claude/kb/` (knowledge). This file, `.cursor/rules/agents-kbs-tech-stack.mdc`, and `.github/copilot-instructions.md` are emitted from those — re-emit with `scripts/emit-cross-tool.sh` after changes.
- **Re-emission triggers:** adding a tech, removing a tech, renaming the project, or changing doctrine.
- **Skill source:** [`agents-kbs-tech-stack`](https://github.com/) — the meta-skill that scaffolds and maintains this layer.

---

Generated by agents-kbs-tech-stack v0.3.0 on {LAST_UPDATED}. Re-emit with `scripts/emit-cross-tool.sh`.
