---
description: Project-wide agents and KB managed by agents-kbs-tech-stack
globs: "**/*"
alwaysApply: false
---

# Agents and Knowledge — managed by agents-kbs-tech-stack

This project's agent definitions and knowledge bases are authoritative under:

- `.claude/agents/` — architect, developer, (optional) troubleshooter, and closer agents
- `.claude/kb/` — per-tech knowledge: quick-reference, concepts, patterns, reference
- `.claude/kb/_index.yaml` — domain index used by closers for runtime grounding
- `.claude/doctrine.yaml` — portable agent contract (Bash boundary, thresholds, closer-hook)
- `AGENTS.md` (repo root) — the cross-tool index; read it first

When assisting with code in files matching these globs, read the appropriate `.claude/agents/<tech>-developer.md` and the matching `.claude/kb/<tech>/` content **before** generating changes. For pre-merge polish (review, simplification, documentation), defer to the closers under `.claude/agents/code-*.md`.

Do not hand-edit this file — it is regenerated by `scripts/emit-cross-tool.sh`.
